//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tutorial.Client.ServiceAdapter.ForumWcfService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ForumWcfService.IForumWcfService")]
    public interface IForumWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumWcfService/SaveForum", ReplyAction="http://tempuri.org/IForumWcfService/SaveForumResponse")]
        Tutorial.Domain.Forum SaveForum(string name, string creator);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumWcfService/SaveForum", ReplyAction="http://tempuri.org/IForumWcfService/SaveForumResponse")]
        System.Threading.Tasks.Task<Tutorial.Domain.Forum> SaveForumAsync(string name, string creator);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumWcfService/UpdateForum", ReplyAction="http://tempuri.org/IForumWcfService/UpdateForumResponse")]
        Tutorial.Domain.Forum UpdateForum(string id, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumWcfService/UpdateForum", ReplyAction="http://tempuri.org/IForumWcfService/UpdateForumResponse")]
        System.Threading.Tasks.Task<Tutorial.Domain.Forum> UpdateForumAsync(string id, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumWcfService/DeleteForum", ReplyAction="http://tempuri.org/IForumWcfService/DeleteForumResponse")]
        void DeleteForum(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumWcfService/DeleteForum", ReplyAction="http://tempuri.org/IForumWcfService/DeleteForumResponse")]
        System.Threading.Tasks.Task DeleteForumAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumWcfService/GetForum", ReplyAction="http://tempuri.org/IForumWcfService/GetForumResponse")]
        Tutorial.Domain.Forum GetForum(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumWcfService/GetForum", ReplyAction="http://tempuri.org/IForumWcfService/GetForumResponse")]
        System.Threading.Tasks.Task<Tutorial.Domain.Forum> GetForumAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumWcfService/CountForum", ReplyAction="http://tempuri.org/IForumWcfService/CountForumResponse")]
        long CountForum();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumWcfService/CountForum", ReplyAction="http://tempuri.org/IForumWcfService/CountForumResponse")]
        System.Threading.Tasks.Task<long> CountForumAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumWcfService/ListForum", ReplyAction="http://tempuri.org/IForumWcfService/ListForumResponse")]
        Tutorial.Domain.Forum[] ListForum();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumWcfService/ListForum", ReplyAction="http://tempuri.org/IForumWcfService/ListForumResponse")]
        System.Threading.Tasks.Task<Tutorial.Domain.Forum[]> ListForumAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IForumWcfServiceChannel : Tutorial.Client.ServiceAdapter.ForumWcfService.IForumWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ForumWcfServiceClient : System.ServiceModel.ClientBase<Tutorial.Client.ServiceAdapter.ForumWcfService.IForumWcfService>, Tutorial.Client.ServiceAdapter.ForumWcfService.IForumWcfService {
        
        public ForumWcfServiceClient() {
        }
        
        public ForumWcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ForumWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ForumWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ForumWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Tutorial.Domain.Forum SaveForum(string name, string creator) {
            return base.Channel.SaveForum(name, creator);
        }
        
        public System.Threading.Tasks.Task<Tutorial.Domain.Forum> SaveForumAsync(string name, string creator) {
            return base.Channel.SaveForumAsync(name, creator);
        }
        
        public Tutorial.Domain.Forum UpdateForum(string id, string name) {
            return base.Channel.UpdateForum(id, name);
        }
        
        public System.Threading.Tasks.Task<Tutorial.Domain.Forum> UpdateForumAsync(string id, string name) {
            return base.Channel.UpdateForumAsync(id, name);
        }
        
        public void DeleteForum(string id) {
            base.Channel.DeleteForum(id);
        }
        
        public System.Threading.Tasks.Task DeleteForumAsync(string id) {
            return base.Channel.DeleteForumAsync(id);
        }
        
        public Tutorial.Domain.Forum GetForum(string id) {
            return base.Channel.GetForum(id);
        }
        
        public System.Threading.Tasks.Task<Tutorial.Domain.Forum> GetForumAsync(string id) {
            return base.Channel.GetForumAsync(id);
        }
        
        public long CountForum() {
            return base.Channel.CountForum();
        }
        
        public System.Threading.Tasks.Task<long> CountForumAsync() {
            return base.Channel.CountForumAsync();
        }
        
        public Tutorial.Domain.Forum[] ListForum() {
            return base.Channel.ListForum();
        }
        
        public System.Threading.Tasks.Task<Tutorial.Domain.Forum[]> ListForumAsync() {
            return base.Channel.ListForumAsync();
        }
    }
}
